name: 🎯 Profiler

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

  workflow_dispatch:
    inputs:
      git-ref:
        description: "git tip: branch/ref/tag"
        required: false
        default: 'main'
      # docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
      js-runtime:
        description: "proc: deno/node"
        required: false
        default: 'node'
        type: choice
        options:
        - node
        - deno
      mode:
        description: "p1 (fetch) / p2 (http2) / p3 (udp/tcp)"
        required: false
        default: 'p1'
        type: choice
        options:
        - p1
        - p2
        - p3
      maxtime:
        description: "run time (in seconds)"
        required: false
        default: '60s'

env:
  GIT_REF: ${{ github.event.inputs.git-ref || github.ref }}
  JS_RUNTIME: 'node'
  MAXTIME_SEC: '30s'
  NODE_VER: '17.x'
  MODE: 'p1'
  QDOH: 'q'

jobs:
  profiler1:
    name: Fetch profiler
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GIT_REF }}

      - name: Set git tip
        run: |
          echo "GIT_HEAD=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "JS_RUNTIME=${JSR}" >> $GITHUB_ENV
        shell: bash
        env:
          JSR: ${{ github.event.inputs.js-runtime || env.JS_RUNTIME }}

      # docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python
      - name: Setup Node @v17
        if: env.JS_RUNTIME == 'node'
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VER }}

      # deno.land/#installation
      - name: Setup Deno @latest
        if: env.JS_RUNTIME == 'deno'
        run: |
          echo "::notice::deno install unsafe"
          curl -fsSL https://deno.land/install.sh | sh
          denohome="/home/runner/.deno/"
          echo "DENO_INSTALL=$denohome" >> $GITHUB_ENV
          echo "$denohome/bin" >> $GITHUB_PATH
        shell: bash

      - name: Download deps
        run: npm i
        # npm ci is faster, but it needs package-lock.json which isn't in main
        # run: npm ci

      - name: Build deps
        run: npm run build --if-present

      # if non-interactive, prefer apt-get: unix.stackexchange.com/a/590703
      # github.com/natesales/repo
      # docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners
      - name: Setup Q
        run: |
          # sudo and echo: stackoverflow.com/a/550808
          echo "deb [trusted=yes] https://repo.natesales.net/apt /" | sudo tee /etc/apt/sources.list.d/natesales.list > /dev/null
          sudo apt-get update
          sudo apt-get install q

      # docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
      # timeout exit-code: stackoverflow.com/a/60996259
      - name: Run profiler
        if: success()
        run: |
          timeout "$MAXTIME_SEC" ./run "$JS_RUNTIME" "$MODE" || ( [[ $? -eq 124 ]] && echo "::notice::Timeout OK" )
        shell: bash
        env:
          MAXTIME_SEC: ${{ github.event.inputs.maxtime || env.MAXTIME_SEC }}
          MODE: ${{ github.event.inputs.mode || env.MODE }}
          TLS_KEY_PATH: 'test/data/tls/dns.rethinkdns.localhost.key'
          TLS_CRT_PATH: 'test/data/tls/dns.rethinkdns.localhost.crt'
